# tput setaf 6; echo "==== MCDM - OREBRO ===="; tput setaf sgr0;
# # Experiments without RFID information
# tput setaf 2; echo "==== wo RFID ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 1 0 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_0_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 1 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_1_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 0 1 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_2_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.33 0.33 0.33 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_3_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.6 0.2 0.2 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_4_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.428 0.428 0.144 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_5_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# tput setaf 7; echo "[1][5/10]"; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.2 0.6 0.2 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_6_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.144 0.428 0.428 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_7_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.2 0.2 0.6 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_8_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.428 0.144 0.428 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_9_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_10_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 0.5 0.5 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_11_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/orebro_small.pgm 1 72 124 180 26 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0 0.5 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_result_orebro_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_coverage_mcdm_orebro_12_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/mcdm_ccuracy_25r.csv
# tput setaf 7; echo "[1][10/10]"; tput setaf sgr0;


# tput setaf 6; echo "==== MCDM - NCFM ===="; tput setaf sgr0;
# # Experiments without RFID information
# tput setaf 2; echo "==== wo RFID ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 1 0 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_0_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 1 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_1_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 0 1 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_2_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.33 0.33 0.33 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_3_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.6 0.2 0.2 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_4_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.428 0.428 0.144 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_5_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# tput setaf 7; echo "[1][5/10]"; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.2 0.6 0.2 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_6_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.144 0.428 0.428 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_7_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.2 0.2 0.6 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_8_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.428 0.144 0.428 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_9_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_10_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 0.5 0.5 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_11_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/ncfm_small.pgm 1 116 90 180 12 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0 0.5 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_result_ncfm_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_coverage_mcdm_ncfm_12_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/ncfm/mcdm_ccuracy_25r.csv
# tput setaf 7; echo "[1][10/10]"; tput setaf sgr0;

tput setaf 6; echo "==== MCDM - INB3123 ===="; tput setaf sgr0;
# Experiments without RFID information
tput setaf 2; echo "==== wo RFID ===="; tput setaf sgr0;
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 1 0 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_0_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 1 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_1_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 0 1 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_2_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.33 0.33 0.33 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_3_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.6 0.2 0.2 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_4_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.428 0.428 0.144 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_5_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
tput setaf 7; echo "[1][5/10]"; tput setaf sgr0;
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.2 0.6 0.2 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_6_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.144 0.428 0.428 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_7_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.2 0.2 0.6 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_8_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.428 0.144 0.428 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_9_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_10_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 0.5 0.5 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_11_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 6 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0 0.5 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_12_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv
tput setaf 7; echo "[1][10/10]"; tput setaf sgr0;


# tput setaf 6; echo "==== MCDM - INBENG ===="; tput setaf sgr0;
# # Experiments without RFID information
# tput setaf 2; echo "==== wo RFID ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 1 0 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_0_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 1 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_1_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 0 1 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_2_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.33 0.33 0.33 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_3_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.6 0.2 0.2 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_4_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.428 0.428 0.144 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_5_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# tput setaf 7; echo "[1][5/10]"; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.2 0.6 0.2 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_6_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.144 0.428 0.428 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_7_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.2 0.2 0.6 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_8_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.428 0.144 0.428 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_9_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_10_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 0.5 0.5 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_11_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0 0.5 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_result_inbeng_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_coverage_mcdm_inbeng_12_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbeng/mcdm_ccuracy_25r.csv
# tput setaf 7; echo "[1][10/10]"; tput setaf sgr0;


# tput setaf 6; echo "==== MCDM - INBATRIUM ===="; tput setaf sgr0;
# # Experiments without RFID information
# tput setaf 2; echo "==== wo RFID ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 1 0 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_0_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 1 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_1_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 0 1 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_2_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.33 0.33 0.33 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_3_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.6 0.2 0.2 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_4_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.428 0.428 0.144 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_5_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# tput setaf 7; echo "[1][5/10]"; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.2 0.6 0.2 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_6_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.144 0.428 0.428 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_7_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.2 0.2 0.6 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_8_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.428 0.144 0.428 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_9_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_10_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0 0.5 0.5 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_11_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# ./../build/mcdm_online_exploration ./../Images/inbatrium_small.pgm 1 72 124 180 9 180 1 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0 0.5 0 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_result_inbatrium_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_coverage_mcdm_inbatrium_12_1.csv /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/distance_tag_25r.csv 1 /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inbatrium/mcdm_ccuracy_25r.csv
# tput setaf 7; echo "[1][10/10]"; tput setaf sgr0;