# tput setaf 6; echo "==== VARIABLE ELLIPSE SIZE - INB3123 - 10 TAGS ===="; tput setaf sgr0;

# # Experiments without RFID information
# tput setaf 2; echo "==== r = [1;7] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 74 77 180 7 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_1a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 101 112 180 7 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_1b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 105 78 180 7 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_1c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# tput setaf 2; echo "==== 1.5r = [1;10] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 74 77 180 10 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_15q.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_15r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 105 78 180 10 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_15b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_15r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 10 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123152c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_ta_15r2.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# tput setaf 2; echo "==== 2r = [1;14] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 74 77 180 14 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_3a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 105 78 180 14 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_3b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 14 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_3c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
# tput setaf 2; echo "==== 4r = [2;27] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 74 77 180 27 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_4a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 2 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 105 78 180 27 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_4b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 2 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 27 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_4c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 2 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# tput setaf 2; echo "==== 5r = [3;38] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 74 77 180 38 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_5a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 105 78 180 38 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_5b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 38 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_5c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# tput setaf 2; echo "==== 6r = [3;45] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 74 77 180 45 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_6a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 105 78 180 45 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_6b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 15 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_6c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# tput setaf 2; echo "==== 11r = [6,77] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 74 77 180 77 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_7a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag7.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 105 78 180 77 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_7b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag7.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 77 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_7c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag7.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# tput setaf 2; echo "==== 0.5m = [1;4] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 74 77 180 4 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_8a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag8.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 105 78 180 4 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_8b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag8.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 4 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_8c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag8.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# tput setaf 2; echo "==== 0.25m = [1;2] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 74 77 180 2 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_9a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag9.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 105 78 180 2 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_9b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag9.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv
# ./../build/mcdm_online_exploration ./../Images/inb3123_small.pgm 1 102 97 180 2 180 0.995 0 1 /home/pulver/mcdm/config/tag_inb3123.yaml 865e6 0 1 0 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inb3123.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inb_3123_9c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag9.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv



tput setaf 6; echo "==== VARIABLE ELLIPSE SIZE - INB_ENG - 10 TAGS ===="; tput setaf sgr0;

# Experiments without RFID information
# tput setaf 2; echo "==== r = [1;9] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_1a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 9 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_1b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 270 9 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_1c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_1d.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 9 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_1e.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 270 9 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_1f.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 9 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_1g.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 9 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_1h.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 270 9 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_1i.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_r.csv
# tput setaf 2; echo "==== 1.5r = [1;15] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 15 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_15a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_15r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 15 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_15b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_15r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 15 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng152c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_ta_15r2.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 15 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_15d.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_15r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 15 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_15e.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_15r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 15 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng152f.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_ta_15r2.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 15 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_15g.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_15r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 15 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_15h.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_15r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 15 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng152i.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_ta_15r2.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_15r.csv
# tput setaf 2; echo "==== 2r = [1;21] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 21 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_2a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 21 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_2b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 21 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_2c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 21 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_2d.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 21 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_2e.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 21 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_2f.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 21 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_2g.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 21 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_2h.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 21 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_2i.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_2r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_2r.csv
tput setaf 2; echo "==== 2.5r = [1;26] cell ===="; tput setaf sgr0;
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 26 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_25a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_25r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 26 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_25b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_25r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 26 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_25c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_25r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 26 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_25d.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_25r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 26 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_25e.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_25r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 26 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_25f.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_25r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 26 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_25g.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_25r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 26 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_25h.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_25r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_25r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 26 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_25i.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_25r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_25r.csv
tput setaf 2; echo "==== 3r = [1;30] cell ===="; tput setaf sgr0;
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 30 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_3a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_3r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_3r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 30 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_3b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_3r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_3r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 30 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_3c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_3r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_3r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 30 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_3d.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_3r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_3r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 30 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_3e.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_3r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_3r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 30 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_3f.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_3r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_3r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 30 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_3g.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_3r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_3r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 30 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_3h.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_3r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_3r.csv
./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 30 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_3i.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag_3r.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_3r.csv
# tput setaf 2; echo "==== 4r = [3;36] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 36 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_4a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 36 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_4b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 36 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_4c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 36 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_4d.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 36 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_4e.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 36 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_4f.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 36 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_4g.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 36 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_4h.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 36 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_4i.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag4.csv 3 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_4r.csv
# tput setaf 2; echo "==== 5r = [5;57] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 57 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_5a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 5 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 57 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_5b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 5 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 57 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_5c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 5 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 57 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_5d.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 5 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 57 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_5e.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 5 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 57 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_5f.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 5 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 57 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_5g.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 5 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 57 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_5h.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 5 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 57 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_5i.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag5.csv 5 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_5r.csv
# tput setaf 2; echo "==== 6r = [6;66] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 66 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_6a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 66 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_6b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 66 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_6c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 66 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_6d.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 66 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_6e.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 66 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_6f.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 66 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_6g.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 66 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_6h.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 66 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_6i.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag6.csv 6 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_6r.csv
# tput setaf 2; echo "==== 11r = [9,114] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 114 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_11a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag11.csv 9 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 114 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_11b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag11.csv 9 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 114 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_11c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag11.csv 9 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 114 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_11d.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag11.csv 9 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 114 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_11e.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag11.csv 9 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 114 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_11f.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag11.csv 9 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 114 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_11g.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag11.csv 9 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 114 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_11h.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag11.csv 9 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 114 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_11i.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag11.csv 9 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_11r.csv
# tput setaf 2; echo "==== 0.5m = [1;5] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 5 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_05a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag05.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 5 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_05b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag05.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 5 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_05c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag05.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 5 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_05d.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag05.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 5 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_05e.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag05.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 5 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_05f.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag05.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 5 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_05g.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag05.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 5 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_05h.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag05.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 5 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_05i.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag05.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_05r.csv
# tput setaf 2; echo "==== 0.25m = [1;3] cell ===="; tput setaf sgr0;
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 3 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_025a.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag025.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 3 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_025b.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag025.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 3 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_1.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_025c.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag025.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 3 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_025d.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag025.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 3 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_025e.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag025.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 3 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_2.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_025f.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag025.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 72 124 180 3 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_025g.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag025.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 79 117 180 3 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_025h.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag025.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv
# ./../build/mcdm_online_exploration ./../Images/inbeng_small_correct.pgm 1 33 45 180 3 180 0.99 0 1 /home/pulver/mcdm/config/tag_inbeng_3.yaml 865e6 0 0.5 0.5 0 0 /home/pulver/Desktop/MCDM/variable_ellipse/result_inbeng.csv /home/pulver/Desktop/MCDM/variable_ellipse/coverage_mcdm_inbeng_025i.csv /home/pulver/Desktop/MCDM/variable_ellipse/distance_tag025.csv 1 /home/pulver/Desktop/MCDM/variable_ellipse/accuracy_025r.csv
